### ISSUE TITLE
Iframe not refreshing when [videoId] changes

### ISSUE THREAD

**Issue by omarlopesino** [orizens/ngx-youtube-player#23] opened 2017-06-26 18:21 UTC
Hi.

I am using this component in my app in this way

`<youtube-player *ngIf="customVideoId != null" [videoId]="customVideoId" [width]="480" [height]="360"></youtube-player>`

But when **customVideoId** variable changes the iframe doesn't reload. The attribute [videoId] is reloaded, but iframe not.

If you give me some guideline to make a PR I can try.

**Comment by orizens** [comment] 2017-06-26 18:26
it should work with an empty string though - try that and let me know.

**Comment by daniyalnagori** [comment] 2017-07-27 15:16
Not working for me also :(

**Comment by Juanperezc** [comment] 2017-08-08 16:58
This also happens with the height and width properties, I would like that when these properties are changed, those of the iframe will also be loaded, for responsive effects.
regards

**Comment by alandrei** [comment] 2017-08-23 11:18
Still happens with dynamic: videoId, height, width.

**Comment by orizens** [comment] 2017-10-03 10:38
hi @mistermoper 
After inspecting this issue, I decided to mark it as not a bug.
it requires interacting with the player object received from the "ready" event, and more development on the component side.

For custom development regarding this - please contact me (details in README.md).

**Comment by moussaDoumbia9219** [comment] 2017-12-29 11:08
You must use the `loadVideoById()` function of player object to update Iframe content dynamically

**Comment by orizens** [comment] 2018-05-30 08:08
closing - reopen to contact.

**Closed as completed by orizens** 2018-05-30 08:08 UTC
Labels: requires license
